### ISSUE TITLE
latest master does not build with python 3.5.2

### ISSUE THREAD

**Issue by protofabrik** [paulscherrerinstitute/pcaspy#32]
Hi, probably not a major issue, however a build fails on latest master [3aa89a49246d59de5cb99369e04ede7d7998b178] using python 3. I did not go into details but I suspect the problem is originating from improper use memory view objects. Builds fine on 2.7.12 though... 

```
python3 setup.py build
running build
running build_py
running build_ext
building 'pcaspy._cas' extension
swigging pcaspy/casdef.i to pcaspy/casdef_wrap.cpp
swig -python -c++ -threads -nodefaultdtor -I/opt/epics/base/include -o pcaspy/casdef_wrap.cpp pcaspy/casdef.i
pcaspy/casdef.i:46: Warning 362: operator= ignored
pcaspy/casdef.i:115: Warning 473: Returning a pointer or reference in a director method is not recommended.
pcaspy/casdef.i:115: Warning 473: Returning a pointer or reference in a director method is not recommended.
creating build
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/pcaspy
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/opt/epics/base/include -I/opt/epics/base/include/os/Linux -I/opt/epics/base/include/compiler/gcc -I/usr/include/python3.5m -c pcaspy/casdef_wrap.cpp -o build/temp.linux-x86_64-3.5/pcaspy/casdef_wrap.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
pcaspy/casdef_wrap.cpp: In function ‘PyObject* _wrap_gdd_putCharDataBuffer(PyObject*, PyObject*)’:
pcaspy/casdef_wrap.cpp:8280:28: error: ‘PyBuffer_Check’ was not declared in this scope
     if (PyBuffer_Check(obj1)) {
                            ^
pcaspy/casdef_wrap.cpp:8281:53: error: ‘Py_END_OF_BUFFER’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                     ^~~~~~~~~~~~~~~~
pcaspy/casdef_wrap.cpp:8281:69: error: ‘PyBuffer_FromObject’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                                     ^
pcaspy/casdef_wrap.cpp: In function ‘PyObject* _wrap_gdd_putShortDataBuffer(PyObject*, PyObject*)’:
pcaspy/casdef_wrap.cpp:8326:28: error: ‘PyBuffer_Check’ was not declared in this scope
     if (PyBuffer_Check(obj1)) {
                            ^
pcaspy/casdef_wrap.cpp:8327:53: error: ‘Py_END_OF_BUFFER’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                     ^~~~~~~~~~~~~~~~
pcaspy/casdef_wrap.cpp:8327:69: error: ‘PyBuffer_FromObject’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                                     ^
pcaspy/casdef_wrap.cpp: In function ‘PyObject* _wrap_gdd_putIntDataBuffer(PyObject*, PyObject*)’:
pcaspy/casdef_wrap.cpp:8372:28: error: ‘PyBuffer_Check’ was not declared in this scope
     if (PyBuffer_Check(obj1)) {
                            ^
pcaspy/casdef_wrap.cpp:8373:53: error: ‘Py_END_OF_BUFFER’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                     ^~~~~~~~~~~~~~~~
pcaspy/casdef_wrap.cpp:8373:69: error: ‘PyBuffer_FromObject’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                                     ^
pcaspy/casdef_wrap.cpp: In function ‘PyObject* _wrap_gdd_putFloatDataBuffer(PyObject*, PyObject*)’:
pcaspy/casdef_wrap.cpp:8418:28: error: ‘PyBuffer_Check’ was not declared in this scope
     if (PyBuffer_Check(obj1)) {
                            ^
pcaspy/casdef_wrap.cpp:8419:53: error: ‘Py_END_OF_BUFFER’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                     ^~~~~~~~~~~~~~~~
pcaspy/casdef_wrap.cpp:8419:69: error: ‘PyBuffer_FromObject’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                                     ^
pcaspy/casdef_wrap.cpp: In function ‘PyObject* _wrap_gdd_putDoubleDataBuffer(PyObject*, PyObject*)’:
pcaspy/casdef_wrap.cpp:8464:28: error: ‘PyBuffer_Check’ was not declared in this scope
     if (PyBuffer_Check(obj1)) {
                            ^
pcaspy/casdef_wrap.cpp:8465:53: error: ‘Py_END_OF_BUFFER’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                     ^~~~~~~~~~~~~~~~
pcaspy/casdef_wrap.cpp:8465:69: error: ‘PyBuffer_FromObject’ was not declared in this scope
       PyObject *buff = PyBuffer_FromObject(obj1, 0, Py_END_OF_BUFFER);
                                                                     ^
error: command 'gcc' failed with exit status 1
```

**Comment by xiaoqiangwang** [comment]
From here https://docs.python.org/3/c-api/objbuffer.html, I was assuming it is only deprecated but continue to work. I need to adapt it to the new protocol.

**Comment by xiaoqiangwang** [comment]
Commit 51ec5d1 add support of the new buffer protocol, and still supports the old support for Python 2.

**Comment by xiaoqiangwang** [comment]
Please use https://github.com/paulscherrerinstitute/pcaspy/issues/28 for further comments.
